# Don't change this! Version used to track needed updates.
version = 0
enderPearlTrail = true
snowballTrailDensity = 0.2
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartSparksDisplayType = "DEFAULT"
minecartSparksDensity = 0.5
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceOozingEffectParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
xpBottleParticlesDisplayType = "DEFAULT"
xpBottleParticlesDensity = 10
eggSmashSound = true

[attacked]
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true

[sleeping]
playerSnoreChance = 0.0
playerSnoreSoundVolume = 0.7000766
playersHaveSleepingZs = true
villagerSnoreChance = 0.2978017769607842
villagerSnoreSoundVolume = 1.0
villagersHaveSleepingZs = true
foxesHaveSleepingZs = true
batsHaveSleepingZs = false
catsHaveSleepingZs = true
otherMobsHaveSleepingZs = false
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubblesDisplayType = "DEFAULT"
drowningBubblesDensity = 6
drowningBubbleAlpha = 1.0
potionRingsDisplayType = "DEFAULT"
potionRingsParticleType = "BOTH"
NPCsHavePotionRings = true

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.4
waitTime = 100
seasons = "WINTER_ONLY"
additionalBiomes = [  ]

[humanoids.player]
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
heartBeatingThreshold = 6
heartbeatVolume = 0.8

[dustClouds]
scale = 2.0
alpha = 1.0
preventWhenRaining = false
flyIntoWall = true
lessViewBlocking = false
playerFell = true
mobFell = true
landMaceAttack = true
playerRunning = false
mobRunning = false
playerRunningRequiresSpeed = true

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true
extinguishSteam = true

[itemRarity]
particlesDisplayType = "OFF"
particleColorType = "NAME_COLOR"
mixedColorName = true
useItemBorder = true
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 1.0

[explosives]
tntUpdateSmoke = true
tntFlamesDensity = 1
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true