copper_nugget_loot = false

["Enabled Copper Overrides"]

	["Enabled Copper Overrides".repeater]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".comparator]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".piston]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".sticky_piston]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".dispenser]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".dropper]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".observer]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".lever]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".powered_rail]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".relayer]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".crank]
		enabled = false
		appearance = false
		recipe = false
		weathering = false
		sound = false

	["Enabled Copper Overrides".cog_block]
		enabled = true
		appearance = true
		recipe = true
		weathering = true
		sound = true

