# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				cow = true
				skeleton = true
				sheep = true
				goat = true
				item = true
				slime = true
				creeper = true
				bat = true
				villager = true
				spider = true
				zombie = true
				glow_squid = true
				allay = true
				enderman = true
				spectral_arrow = true
				pig = true
				blaze = true
				experience_orb = true

			[light_sources.settings.entities.quark]
				toretoise = true
				stoneling = true

			[light_sources.settings.entities.caverns_and_chasms]
				peeper = true
				deeper = true
				lost_goat = true
				glare = true
				mime = true

			[light_sources.settings.entities.savage_and_ravage]
				skeleton_villager = true

